version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: t_sub_2208
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:t_sub_2208@db:5432/postgres
volumes:
  db-data:
